
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEleftEXPrightUMINUSDIVIDE EQUALS EXP FLOAT LPAREN MINUS NAME NUMBER PLUS RPAREN TIMESstatement : NAME EQUALS expressionstatement : expression\n        expression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expression\n                  | expression EXP expression\n        expression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : NUMBERexpression : FLOATexpression : NAME'
    
_lr_action_items = {'NAME':([0,4,5,8,9,10,11,12,13,],[2,15,15,15,15,15,15,15,15,]),'MINUS':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,],[4,-12,10,4,4,-10,-11,4,4,4,4,4,4,-8,-12,10,10,-3,-4,-5,-6,-7,-9,]),'LPAREN':([0,4,5,8,9,10,11,12,13,],[5,5,5,5,5,5,5,5,5,]),'NUMBER':([0,4,5,8,9,10,11,12,13,],[6,6,6,6,6,6,6,6,6,]),'FLOAT':([0,4,5,8,9,10,11,12,13,],[7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,6,7,14,15,17,18,19,20,21,22,23,],[0,-12,-2,-10,-11,-8,-12,-1,-3,-4,-5,-6,-7,-9,]),'EQUALS':([2,],[8,]),'PLUS':([2,3,6,7,14,15,16,17,18,19,20,21,22,23,],[-12,9,-10,-11,-8,-12,9,9,-3,-4,-5,-6,-7,-9,]),'TIMES':([2,3,6,7,14,15,16,17,18,19,20,21,22,23,],[-12,11,-10,-11,-8,-12,11,11,11,11,-5,-6,-7,-9,]),'DIVIDE':([2,3,6,7,14,15,16,17,18,19,20,21,22,23,],[-12,12,-10,-11,-8,-12,12,12,12,12,-5,-6,-7,-9,]),'EXP':([2,3,6,7,14,15,16,17,18,19,20,21,22,23,],[-12,13,-10,-11,-8,-12,13,13,13,13,13,13,-7,-9,]),'RPAREN':([6,7,14,15,16,18,19,20,21,22,23,],[-10,-11,-8,-12,23,-3,-4,-5,-6,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,5,8,9,10,11,12,13,],[3,14,16,17,18,19,20,21,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','Lua.py',134),
  ('statement -> expression','statement',1,'p_statement_expr','Lua.py',139),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','Lua.py',146),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','Lua.py',147),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','Lua.py',148),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','Lua.py',149),
  ('expression -> expression EXP expression','expression',3,'p_expression_binop','Lua.py',150),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','Lua.py',167),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','Lua.py',173),
  ('expression -> NUMBER','expression',1,'p_expression_number','Lua.py',178),
  ('expression -> FLOAT','expression',1,'p_expression_float','Lua.py',182),
  ('expression -> NAME','expression',1,'p_expression_name','Lua.py',186),
]
